# Configuração inicial
# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute


# index: 
#     path: /
#     controller: App\Controller\DefaultController::index